### ISSUE TITLE
Test download script

### ISSUE THREAD

**Issue by rvosa** [naturalis/apexomes#1]
As of commit 654c0d0c113249d21f117bf154099bff1b29664b there is now a script that downloads all the FASTQ files and the file with [MD5 checksums](https://en.wikipedia.org/wiki/Md5sum) that was computed on the side of LUMC. To ensure that all downloads completed successfully we must compute these checksums on our end as well and then compare the observed and expected values. The download script does that, and deletes any incomplete/failed downloads.

Your task is to do the following:
1. make sure that the variable `DATADIR` is defined correctly in the script. This variable must define where we are going to store the reads. This must be a location inside the data volume, NOT the storage for the instance itself. If the mountpoint of the data volume is `/foo/bar`, and inside it there is a folder called `reads`, then the location must therefore be `/foo/bar/reads`.
2. make sure that the rest of the script works as expected. The script depends on the downloader `wget`, so check to see if this is indeed installed, e.g. using `which wget`, which should return the location of the executable. The same applies to the program that computes the checksum, i.e. `md5sum`. If either of these are missing, install them using `sudo apt-get ...`.
3. check to make sure that there are no errors in the script. If you find any errors, correct them AND COMMIT THE CORRECTIONS BACK TO THE REPOSITORY.

Once these steps are done and it all works, make a reply to this issue noting the commit at which point it was all working, then close the issue.

(Also notifying Dick of this issue: @dickgroenenberg)

**Comment by sdevriend** [comment]
I have tested the script and I noticed an error with the ssl certificate from the LUMC. I am not sure if the error is provoked by eduraom or something else. I could work around by adding an option to wget:
--no-check-certificate
If it is allowed to download the data without the ssl check, I will push the new version to git.

**Comment by rvosa** [comment]
Good job - yup, I don't think we need to worry about the SSL certificates. As long as the MD5 sums check out it should be fine. Please commit this back to the repo!

**Comment by sdevriend** [comment]
The files have been deleted from the LUMC servers so this script doesn't have the correct urls. Is there a place on the naturalis network to put the files for downloading by this script? Because it is not possible to wget files from google drive. Is git lfs an option? 
[Pricing for extra storage](https://help.github.com/articles/billing-plans-for-git-large-file-storage/)
