### ISSUE TITLE
organiseren van /mnt/data

### ISSUE THREAD

**Issue by rvosa** [naturalis/apexomes#10]
De structuur van het data volume moet zodanig zijn dat een nieuwkomer in het project snapt wat wat is. Dat wil zeggen een logische organisatie met voldoende READMEs die uitleg geven. Alle ruwe input data moet op READ ONLY gezet worden. Voor de duidelijkheid, deze ruwe data zijn dus:
- de gecomprimeerde FASTQ bestanden met exoomdata
- de VCF bestanden die we ooit hebben gedownload
- het referentiegenoom

Als dit gedaan is dan kunnen #1 en #4 ook gesloten worden.

**Comment by rvosa** [comment]
Op het data volume staan alleen maar de drie gorilla bestanden, maar niet de orangoetan bestanden. Is het dus zo dat die ergens op een google drive staan?

**Comment by dickgroenenberg** [comment]
De Orangutan data staan nog niet op de Drive. Ik beschik wel over een backup op mijn harde schijf, maar heb die destijds zonder Checksum gedownload.. De bestanden zijn nog steeds gezipt en de grootte was voor zover ik mij kan herinneren gelijk aan die op de LUMC server.
