### ISSUE TITLE
bijwerken lokale clone

### ISSUE THREAD

**Issue by rvosa** [naturalis/apexomes#12]
Op de instance staat een clone van de repo die i) achterloopt met de repo op github ii) scripts bevat die niet op github staan.

Degene die die scripts heeft gemaakt moet op de instance het volgende doen:
1. een `git pull` om bij te werken tot de huidige situatie op github
2. troep en experimenten die niet op github hoeven, verwijderen 
3. belangrijke scripts die nog niet op github staan toevoegen (`git add`, `git commit`, `git push`)

**Comment by rvosa** [comment]
Laat maar, waren alleen maar tussentijdse *.save bestanden.

**Comment by dickgroenenberg** [comment]
Inmiddels de scripts weer gevonden..
Is het de bedoeling dat deze in /usr/local/src/apexomes/script staan?
Volgens mij stonden alle scripts inderdaad op Github, maar for the record:
Hoe kwam je erachter welke scripts niet op Github stonden?

**Comment by rvosa** [comment]
Je kan met 'git status' zien of scripts gesynchroniseerd zijn met github.

2016-06-23 2:12 GMT-05:00 dickgroenenberg notifications@github.com:

**Comment by dickgroenenberg** [comment]
..maar geeft 'git status' geeft toch alleen het verschil tussen een Github repository en een locale kloon? Hoe is dit gelinkt aan het Apexome instance (/usr/local/src/apexomes/script)?
Bestaat er een synchronisatie tussen ons instance en Github?

**Comment by rvosa** [comment]
/usr/local/src/apexomes/script is onderdeel van een lokale kloon, dus daar
zou je 'git status' moeten kunnen doen. Toch? Zullen we er morgen even naar
kijken?
