### ISSUE TITLE
Trim input output

### ISSUE THREAD

**Issue by gbbio** [naturalis/apexomes#15]
Als "eerste gebruiker" loop ik nu tegen iets aan. Ik wil de pipeline runnen met Orang-oetan exomen en deze exomen staan nu allemaal in dezelfde map (niks mis mee lijkt mij). Om ze door de pipeline te halen zou ik ze eerst allemaal in aparte mappen moeten zetten. Na het trimmen ontstaat er dan ook weer voor elk exoom een aparte map en elk getrimde fastq bestand krijgt dezelfde naam, wat later misschien erg lastig kan zijn. Zou dit niet anders moeten? Gezien ik waarschijnlijk 13 genomen/exomen ga gebruiken staat er straks 26 mappen op de server en heb ik 13 getrimde bestanden met dezelfde naam.

**Comment by dickgroenenberg** [comment]
Zoals aangegeven valt voor beide situaties - alleen naam output map uniek - of bestanden daarin uniek - wat te zeggen. Rutger gaf aan dat het wat hem betreft niet uitmaakt, zolang het maar duidelijk is, wat wat is. Aangezien het feit dat verderop in de pipeline vermoedelijk de standaard ongewijzigde outputnamen worden gebruikt - en het dan dus meer werk wordt de pipeline daarop aan te passen - denk ik met oog op de beperkte tijd, dat het verstandiger is dit zo te laten.
