### ISSUE TITLE
Pick the right reference genome

### ISSUE THREAD

**Issue by rvosa** [naturalis/apexomes#3]
It appears we may be using the wrong release of the gorilla reference genome (https://github.com/naturalis/apexomes/blob/master/script/DownloadGenome.sh#L53), should be this one: http://ftp.ensembl.org/pub/release-71/fasta/gorilla_gorilla/dna/

**Comment by sdevriend** [comment]
That was a testing file. I've added the correct genome. I will cleanup the old files if everything works on the openstack machine. c56cccc22f90b971039ffb2412905e0679c451ad
