### ISSUE TITLE
Unable to download vcf files

### ISSUE THREAD

**Issue by sdevriend** [naturalis/apexomes#4]
When I try to download the vcf files that where committed on 69e53b3b4f8b0a49668fae16b9c1b04559c1273f
I get an error on linux and on windows.
- Windows:

> Git LFS is disabled for this repository.
> Request:Status=403 Forbidden
-  Linux:

> (0 of 46 files) 0 B / 6.01 GB
> This repository is over its data quota. Purchase more data packs to restore access.
> Docs: https://github.com/contact
> Warning: errors occurred

I don't know if this error occurd because a mistake on my account, or that indeed the storage quota of this rep had exceeded it's limit.

**Comment by rvosa** [comment]
This has to do with the fact that the Naturalis institutional account is not yet paying for git-LFS, so this approach might actually not yet be available. I have the data locally, let me know how I can transfer it to you (~6Gb).

**Comment by rvosa** [comment]
Irrelevant: 7729d2566e383b44462572c5a22f9dc2101b17d2
