### ISSUE TITLE
backup problemen, opschonen

### ISSUE THREAD

**Issue by rvosa** [naturalis/apexomes#7]
Beste mensen,

ik heb daarnet even rondgekeken in de apexomes instance en er zijn een aantal onhygiënische dingen aan de hand die het project in de weg zitten, en dan met name ons vermogen om backups te maken, instances opnieuw in te richten, en anderen (bv. nieuwe studenten) wegwijs te maken in het project. Het zou goed zijn om deze zaken aan te pakken:
- [x] er zijn vele gigabytes aan data opgeslagen in ~/DG. Als dat geen afval is, verplaats het dan naar /mnt/data, anders verwijderen.
- [x] in de home directory zijn een aantal tools gedownload en uitgepakt. Worden die gebruikt? Staan die in het PATH? 
- [x] de organisatie van /mnt/data is niet helder. De volgende persoon die hier gaat kijken zal niets kunnen terugvinden. Wat strategisch geplaatste READMEs met uitleg wat wat is zijn echt nodig.

Er is een backup_data folder die geen nut lijkt te dienen maar wel vele gigabytes in beslag nam. Voorzover deze folder integrale kopieën van data elders bevat heb ik deze vervangen met symlinks. Mijn gedachte was dat er wellicht scripts zijn die iets doen met de bestanden in backup_data; met behulp van een goedkope symlink blijft dat gewoon werken zonder ruimte te vreten. Deze ingreep moet ook gebeuren voor Blij_Thirza, MAAR:
- [x] wat er is gebeurd met Blij_Thirza is niet duidelijk: de gelijknamige bestanden in de root (dus /mnt/data/Blij_Thirza) en in de backup_data folder wijken van elkaar af qua grootte. De bestanden in backup_data komen qua MD5 checksum overeen met wat op 30/11/2015 is berekend door de studenten, dus waarschijnlijk zijn dat de originelen. Deze bestanden zijn ook ongeveer 1 gigabyte groter dan die in de root. Als de bestanden in backup_data inderdaad de originelen zijn en de anderen een soort tussenstap die ook opnieuw gegenereerd kan worden, doe dan als volgt: i) kopieer de originelen naar de root, ii) zet deze originelen op readonly iii) maak symlinks naar de originelen vanuit backup_data/Blij_Thirza. M.a.w., dezelfde benadering als Blij_Sandra en Boer_Azoux.

Dit alles om toe te werken naar een logische manier van backuppen, die ongeveer als volgt zou moeten zijn:
- alle scripts zijn onderdeel van de apexomes repo en worden daar gecommit. Op dit moment zijn er scripts in ~/apexomes die niet voorkomen in de repository op github. Dat moet niet.
- in principe zou het zo moeten zijn dat het optuigen van de bootable instance (dus niet het datavolume) kan gebeuren door een nieuwe Ubuntu 14.04LTS in te richten en daar een provisioning op uit te voeren. De stappen voor deze provisioning moeten ook op github staan, d.w.z. iets als een puppet manifest, of desnoods een shell script dat alle tools download (in /usr/local/src wellicht) en installeert. Op deze manier kan de instance makkelijk weer opnieuw ingericht worden en is een snapshot daarvan dus niet nodig.
- het data volume verwijst in principe naar "immutable" ruwe data (readonly, onaangeraakt) die van een soort centrale library afkomstig zijn, alle tussenstappen tot aan resultaten zijn geautomatiseerd (en hoeven dus niet gebackupt), alleen de resultaatsdata zijn interessant en moeten op een bepaalde manier periodiek opgeslagen worden, maar wellicht zijn die zo klein dat dat gewoon op github kan. Een redelijk alternatief zou zijn om puur een snapshot van het data volume te maken.

Zullen we gedrieën ongeveer hiernaartoe gaan werken? Of ten minste naar een ander, doordacht alternatief?

**Comment by JeroenPijpe** [comment]
Toen ik Sigrid Beiboer heb ingewerkt op de instance zag ik al dat het datavolume vrij leeg was en dat er veel grote bestanden op de instance stonden. Ik kan enkele voorgestelde taken (verplaatsen en organiseren/verwijderen data) wel op me nemen op korte termijn (volgende week vrijdag). Het opstellen van een werkend shell of puppet script kost me meer tijd. Misschien toch bpsda-student Sebastiaan de Vriend inschakelen voor de onduidelijke zaken rondom de Back-up folder?

Wat is de deadline? Bio-informatica Student Marten start 27 juni zijn ministage van een week of 4.

**Comment by hduijn** [comment]
Bij ons ICT-Infra is het verzoek gekomen op data te waarborgen middels backup. De basis is dat we een IAAS model aanbieden dus liever ook de backup overlaten aan de gebruikers van de omgeving, daarbij kunnen we uiteraard wel zorg dragen voor hulp en eventueel resources. 

Zorgen dan het systeem geheel vanuit schone Ubuntu installatie middels scripts van Github provisioned kan worden betekend al dat er geen noodzaak is voor een systeem backup. Het data volume excl. onderzoeksresultaten is ook opnieuw aan te maken eventueel onderzoeksresultaten op Github of gedeelde afdeling mappen zou betekenen dat ook daarvoor geen backup noodzakelijk is. Wellicht is dit voor het data volume op dit moment nog een wens en geen werkelijkheid en dan kan een snapshot van het datavolume uitkomst bieden. Een snapshot mag niet gezien worden als volwaardige backup gezien het op hetzelfde storage cluster staat als de primaire storage, een grote calamiteit in het datacenter kan dan in verlies van data resulteren, indien dat niet acceptabel is dan kan ICT-Infra de snapshot op verzoek kopieren naar het backup cluster. 

Graag hoor ik of het gewenst is een snapshot te kunnen maken van het volume zodat ik dan de quota's van het project kan ophogen.

**Comment by rvosa** [comment]
Hi @hduijn,

erg fijn dat je meedenkt! De situatie die we moeten zien te bereiken is dat ALLE data, helder georganiseerd, op het datavolume staan. Als dat gelukt is (zover zijn we nog niet) dan zouden we inderdaad graag een snapshot willen maken van het datavolume, dat vervolgens gekopieerd wordt naar het backup cluster.

De stappen die genomen moeten worden voordat het zin heeft om te snapshotten en backuppen, zijn (zoals boven ook al omschreven):
- [x] Waar nodig, verplaatsen van data in ~/DG naar data volume. Waarschijnlijk is ~/DG aangemaakt
  door @dickgroenenberg, dus hij zou dit moeten oplossen.
- [x] Uitsluitsel geven over wat er met Blij_Thirza is gebeurd en de data op dezelfde manier organiseren 
  als de andere twee individuen. Waarschijnlijk kan @sdevriend hierbij uitsluitsel geven.
- [x] Organiseren van /mnt/data, toevoegen van READMEs. Kunnen we samen doen.

De aanname is dan dat de andere artefacten van het project (de scripts en de werkomgeving) niet door ICT gebackupt hoeven te worden, want:
- [x] De scripts staan op github. Hierbij moeten @sdevriend en @dickgroenenberg bepalen wat er moet
  gebeuren met scripts die wel op de instance, maar niet op de repo staan.
- [x] De werkomgeving kan automatisch opnieuw gegenereerd worden, d.w.z. alle gebruikte tools 
  worden geinstalleerd door een puppet manifest (dat ook op de repo staat). Kunnen we samen doen.

**Comment by rvosa** [comment]
Ok, om het allemaal ietsje behapbaarder te maken zonder deze lappen tekst heb ik dit issue nu opgesplitst in een aantal kleine taken (#8, #9, #10, #11, #12) en deze toegewezen aan de waarschijnlijk meest relevante persoon. Dit zijn allemaal kleine klusjes. Als er een af is, graag de issue sluiten zodat we kunnen zien of we de [milestone](https://github.com/naturalis/apexomes/milestones/Gereedmaken%20voor%20backups) aan het bereiken zijn.
