### ISSUE TITLE
opschonen ~/DG

### ISSUE THREAD

**Issue by rvosa** [naturalis/apexomes#8]
De "scribble" data van @dickgroenenberg staan op de verkeerde plek, namelijk op de instance i.p.v. het data volume. Dick, als je klaar bent met het opschonen hiervan, wil je dan deze ticket sluiten?

**Comment by rvosa** [comment]
Waarschijnlijk is het zo dat een belangrijk deel in /mnt/data/intermediate terecht moet komen, waarna #10 min of meer afgerond is.

**Comment by dickgroenenberg** [comment]
De map DG is opgeschoond waardoor hij op dit moment nog ~17 Gb groot is.
De map is verplaatst naar /mnt/data/intermediate. Er is een README bestand
toegevoegd wat de inhoud beschrijft en waarom het handig is deze bestanden
(voorlopig) nog even te bewaren.

Nu blijft er in de homefolder alleen nog een map "test" over; ook ooit door de
studenten gemaakt. Naast wat *.vcf bestanden bevat het een script "VCFcreate.sh"
dat ik niet in het Github repository terug kan vinden..
